source .env

MODULE_NAME=pio_db

docker build $PWD/db -t $MODULE_NAME
docker run --name $MODULE_NAME \
  -e POSTGRES_USER=$POSTGRES_USER \
  -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
  -e POSTGRES_DB=$POSTGRES_DB \
  -p 5432:5432 \
  $MODULE_NAME